apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: alloydb
build:
  tagPolicy:
    envTemplate:
      template: "latest"
  artifacts:
    - image: alloydb/local
      context: ./alloydb
  local:
    push: false
    useBuildkit: true
profiles:
  - name: local
    activation:
      - env: ENV=local
      - kubeContext: minikube
        command: dev
    manifests:
      kustomize:
        paths:
          - ./.k8s/overlays/local
    deploy:
      kubectl: {}
